title: JINYU's Homepage
page-top-title: </font> <font face="Times New Roman">XIA Jinyu</font>
top-section-bg-text: Be what you wanna be
home-subtitle: â€ğŸ“ <font face="åæ–‡æ¥·ä½“"> å¤é‡‘å®‡</font> &ensp;|&ensp;</font> <font face="Times New Roman">Jinyu Xia</font>
copyright-text: '&copy; Jinyu Xia 2023-2026. All Rights Reserved.'
