title: JINYU's Homepage
page-top-title: XIA Jinyu
top-section-bg-text: Be what you wanna be
home-subtitle: YXIA Jinyu &ensp;|&ensp;夏金宇
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
